<a href="https://colab.research.google.com/github/kmdadoo/pythonNumpy/blob/main/Section04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Section 4. N차원 배열 정렬

---



###**4-1. 1차원 배열의 정렬**

In [ ]:
arr = np.random.randint(10, size=10)
print(arr)

[9 5 8 1 9 8 1 9 0 2]


In [ ]:
# 1차원 배열 오름차순 정렬하기
print(np.sort(arr))

[0 1 1 2 5 8 8 9 9 9]


In [ ]:
# 1차원 배열 내림차순 정렬하기
print(np.sort(arr)[::-1]) # 처음부터 끝까지 마이너스 한칸 간격으로 인덱싱 해주는 것

[9 9 9 8 8 5 2 1 1 0]


In [ ]:
# 값을 유지 하려면
arr1 = np.random.randint(10, size=10)
print(arr1)
arr1 = np.sort(arr1) # 변수에 새로 할당 해 주거나
print(arr1)

arr2 = np.random.randint(10, size=10)
print(arr2)
arr2.sort() # 재정의 된 sort()함수를 이용해서 출력
print(arr2)

[4 7 7 6 3 3 2 9 5 2]
[2 2 3 3 4 5 6 7 7 9]
[6 5 2 7 8 9 1 8 4 6]
[1 2 4 5 6 6 7 8 8 9]


###**4-2. 2차원 배열의 정렬**

In [ ]:
arr = np.random.randint(15, size=(3, 4))
print(arr)

[[11  7  4 13]
 [ 8  5 10  7]
 [ 4 10  7  8]]


In [ ]:
# 2차원 배열 row 기준 정렬하기 : 기본 정렬임.
print(np.sort(arr))

[[ 4  7 11 13]
 [ 5  7  8 10]
 [ 4  7  8 10]]


In [ ]:
# 2차원 배열 column 기준 정렬하기
print(np.sort(arr, axis=0))

[[ 4  5  4  7]
 [ 8  7  7  8]
 [11 10 10 13]]


In [ ]:
# 1차원 배열로 변경하여 전체 배열 정렬하기
print(np.sort(arr, axis=None))

[ 4  4  5  7  7  7  8  8 10 10 11 13]


In [ ]:
# 배열을 정렬할 index 출력하기 : argsort()
arr = np.random.randint(15, size=(3, 4))
print(arr)
print(np.sort(arr, axis=1))
print(np.argsort(arr, axis=1))  # 원래 자기 행의 위치의 인덱스를 출력

[[ 1  3 14  2]
 [ 6  4  6  5]
 [ 2 14  3 11]]
[[ 1  2  3 14]
 [ 4  5  6  6]
 [ 2  3 11 14]]
[[0 3 1 2]
 [1 3 0 2]
 [0 2 3 1]]


In [ ]:
# 배열을 정렬할 index 출력하기 : argsort()
arr = np.random.randint(15, size=(3, 4))
print(arr)
print(np.sort(arr, axis=0))
print(np.argsort(arr, axis=0))  # 원래 자기 열의 위치의 인덱스를 출력

[[ 6  1 11  4]
 [ 0 10  6 12]
 [ 4  0 13  7]]
[[ 0  0  6  4]
 [ 4  1 11  7]
 [ 6 10 13 12]]
[[1 2 1 0]
 [2 0 0 2]
 [0 1 2 1]]
